config/routes.rb
QuickieMeet::Application.routes.draw do
  devise_for :users,  controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "users"}
  

    resources :users do
      member do 
        get 'profile'
        get 'sign_up_success' 
      end
    end

   root :to => 'home#index'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  attr_accessible :meeting_details, :meeting_time
  has_many :users, :through => :user_meetings
  has_many :user_meetings
end

app/models/need.rb
class Need < ActiveRecord::Base
	attr_accessible :title
	belongs_to :user
end

app/models/offering.rb
class Offering < ActiveRecord::Base
  attr_accessible :title
  belongs_to :user
end

app/models/user.rb
 class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :company_url, :linked_public_profile, :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :provider, :uid, :company_name, :zip_code, :needs, :offerings, :google_plus_profile_url, :skype, :phone, :needs_attributes, :offerings_attributes, :linked_in_image_url
  
	attr_writer :current_step

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :email, :uniqueness => true
  validates :zip_code, :numericality => { :only_integer => true }, :allow_blank => true
  validates :phone, :numericality => { :only_integer => true }, :allow_blank => true
  validates :company_url,
            :length => { :maximum => 100, :allow_nil => true, :allow_blank => true},
            :format => { :with => URI::regexp, :allow_nil => true, :allow_blank => true}
  validates :google_plus_profile_url,
            :length => { :maximum => 100, :allow_nil => true, :allow_blank => true},
            :format => { :with => URI::regexp, :allow_nil => true, :allow_blank => true}          

  has_many :needs
  has_many :offerings
  has_many :meetings, :through => :user_meetings
  has_many :user_meetings
  accepts_nested_attributes_for :needs
  accepts_nested_attributes_for :offerings

  def self.from_omniauth(auth)
  	where(auth.slice(:provider, :uid)).first_or_create do |user|
  		user.provider = auth.provider
  		user.uid = auth.uid
  		user.first_name  = auth.info.first_name
  		user.last_name = auth.info.last_name
  		user.email = auth.info.email
  	end
  end

  def current_step
  	@current_step || steps.first
	end

  def steps
  	%w[about need offering ways_to_connect]
	end

	def next_step
	  self.current_step = steps[steps.index(current_step)+1]
	end

	def previous_step
	  self.current_step = steps[steps.index(current_step)-1]
	end

	def first_step?
	  current_step == steps.first
	end

	def last_step?
	  current_step == steps.last
	end

  def name
    first_name + " " + last_name
  end
end

app/models/user_meeting.rb
class UserMeeting < ActiveRecord::Base
  attr_accessible :user_id, :meeting_id
  belongs_to :meeting
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end
	
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController <  Devise::OmniauthCallbacksController
	skip_before_filter :require_no_authentication, :only => [:new, :create]

	def all
		#linkedin_user = User.from_omniauth(request.env["omniauth.auth"])
		#sign_in :user, linkedin_user
		auth = request.env["omniauth.auth"]
		session[:user_data_from_linkedin] = {:first_name => auth.info.first_name, :last_name => auth.info.last_name, :email => auth.info.email, :provider => auth.provider, :uid =>  auth.uid, :linked_in_image_url => auth.info.image, :linked_public_profile => auth.info.urls.public_profile}
		redirect_to new_user_path
	end
	alias_method :linkedin, :all
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :authenticate_user!, :except => [:create, :new, :edit]

	def index
	end

	def new
		@user = User.find_by_uid(session[:user_data_from_linkedin][:uid])
		if @user
			session[:user_data_from_linkedin] = nil
			sign_in :user, @user
			redirect_to profile_user_path(@user)
		else
			session[:user_params] ||= session[:user_data_from_linkedin] 
			@user = User.new(session[:user_params])
			5.times {@user.needs.build}
			5.times {@user.offerings.build}
			@user.current_step = session[:user_step]
		end
	end

	def profile
		@user = User.find(params[:id])
	end

	def create
		session[:user_params].merge!(params[:user]) if params[:user]
		@user = User.new(session[:user_params])
		@user.current_step = session[:user_step]
		if @user.valid?
			if params[:back_button]
				@user.previous_step
				5.times {@user.needs.build} if @user.needs.size == 0
				5.times {@user.offerings.build} if @user.offerings.size == 0
			elsif @user.last_step?
				@user.save
			else
				@user.next_step
				5.times {@user.needs.build} if @user.needs.size == 0
				5.times {@user.offerings.build} if @user.offerings.size == 0
			end
			session[:user_step] = @user.current_step
		end
		if @user.new_record?
    	render "new"
  	else
	    session[:user_step] = session[:user_params] = nil
	    flash[:notice] = "User saved!"
	    sign_in :user, @user
	    redirect_to sign_up_success_user_path(@user) 
  	end
	end

	def edit
		@user = User.find(params[:id])
	end

	def sign_up_success
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update_attributes(params[:user])
		redirect_to profile_user_path(@user)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def image_url(user)
		user.linked_in_image_url.nil? ? "Profile-Picture.png": user.linked_in_image_url
	end

	def button_name(user)
		if user.new_record?
			user.last_step? ? "Complete" : "Next"
		else
			"Update"
		end
	end


	def upcoming_meetings(user)
		@user.meetings.where("meeting_time > :today_time", :today_time => Time.now)
	end

	def past_meetings(user)
		@user.meetings.where("meeting_time < :today_time", :today_time => Time.now)
	end

	def meeting_with(meeting)
		user = meet.users.where("users.id != :current_user", :current_user => current_user.id)
		user.first.name
	end


	def offers_matching(user)
		user_needs = []
		user_needs = user.needs.collect {|need| user_needs << need if need.present? }
		offer_matching = Offering.where("offerings.title IN (?)",user_needs) 
	end

	def needs_matching(user)
		user_offerings = []
		user_offerings = user.offerings.collect {|offering| user_offerings << offering if offering.present? }
		Need.where("needs.title IN (?)",user_offerings)
	end

	def user_needs(user)
		user_needs = []
		user_needs = user.needs.collect {|need| user_needs << need if need.present? }
		user_needs.join(", ")
	end

	def user_offerings(user)
		user_offerings = []
		user_offerings = user.offerings.collect {|offering| user_offerings << offering if offering.present? }
		user_offerings.join(", ")
	end
end

app/views/home/index.html.erb
    <div class="container">
    	<div class="row">
    		<div class="span2">
	      	<h3 class="muted">Quikie Meet</h3>    			
    		</div>
        <div class="span2">
                    
        </div>
	        <div class="navbar span4">
	          <div class="navbar-inner">
	            <div class="container">
	              <ul class="nav">
	                <li class="active"><a href="#">Home</a></li>
	                <li><a href="#">Learn</a></li>
	                <li><a href="#">About</a></li>
	                <li><a href="#">Careers</a></li>
	                <li><a href="#">News</a></li>
	              </ul>
	            </div>
	          </div>
	        </div>
	        <div class="span1">
	        	<%= link_to "Sign in", user_omniauth_authorize_path(:linkedin), :class => "btn btn-primary"%> 
	        </div>
      </div>
    
    <div class=container"">
      <div class="hero-unit">
        <div class="row">
          <div class="span5">
            <iframe src="http://player.vimeo.com/video/59379393" width="400" height="200" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
          </div>
          <div class="span4">
            <%= link_to "Sign up with LinkedIn", user_omniauth_authorize_path(:linkedin), :class => "btn btn-block  btn-large btn-primary"%> 
          </div>
        </div>
      </div>
    </div>
    <div class=container"">
        <div class="row">
          <div class="span5">
            <iframe src="http://player.vimeo.com/video/59379393" width="400" height="200" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
          </div>

          <div class="span4">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.         
          </div>
        </div>
    </div>    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>QuickieMeet</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= yield %>
	</body>
</html>

app/views/users/_about.html.erb
	<h2 class="form-signin-heading">Tell Us About Your Self</h2>
	<%= f.text_field :first_name, :class => "input-block-level", :placeholder =>  "First Name"%>
	<br>
	<%= f.text_field :last_name, :class => "input-block-level", :placeholder => "Last Name" %>
	<br>
	<%= f.text_field :company_name, :class => "input-block-level", :placeholder => "Comapany Name" %>
	<br>
	<%= f.text_field :company_url, :class => "input-block-level", :placeholder => "Comapany Url" %>
	<%= f.text_field :zip_code, :class => "input-block-level", :placeholder => "Zip Code" %>

app/views/users/_final.html.erb
<div class="">
	<h3>Congrats</h3>
	You're all done. Now get ready for us to do all the work and find you what you are looking for. 
</div>

app/views/users/_form.html.erb
	
	<%= form_for @user, :html => { :class => "form-signin", :autocomplete=>"off"} do |f| %>
	  <% if @user.errors.any? %>
		  <div id="errorExplanation" class="alert">
		    <ul>
		    <% @user.errors.full_messages.each do |msg| %>
		      <li><%= msg %></li>
		    <% end %>
		    </ul>
		  </div>
	  <% end %>
	  <%if @user.new_record?%>	
			<%= render "#{@user.current_step}", :f => f %>
		<%else%>
			<%= render "about", :f => f %>
			<%= render "need", :f => f %>	
			<%= render "offering", :f => f %>	
			<%= render "ways_to_connect", :f => f %>
		<%end%>
		<%= f.hidden_field :linked_in_image_url%>
		<%= f.hidden_field :linked_public_profile%>
		<div class="container">
			<div class="row">
				<div class="span2">
					<p><%= f.submit "Back", :name => "back_button",  :class => "btn btn-primary" unless @user.first_step? %></p>
				</div>
				<div class="span7">		
		  		<p><%= f.submit button_name(@user), :class => "btn btn-primary" %></p>
		  	</div>
		  </div>
		</div>
	<%end%>

app/views/users/_need.html.erb
<h2 class="form-signin-heading">I Need</h2>
<%= f.fields_for :needs do |builder| %>
	<%= builder.text_field :title, :class => "input-block-level", "data-provide"=>"typeahead", "data-items"=>"4", "data-source"=>"[&quot;designer&quot;,&quot;Attorney&quot;,&quot;painter&quot;,&quot;Accountant&quot;]".html_safe %>
<%end%>

app/views/users/_offering.html.erb
<h2 class="form-signin-heading">I am offering<h2>
<%= f.fields_for :offerings do |builder| %>
	<%= builder.text_field :title, :class => "input-block-level", "data-provide"=>"typeahead", "data-items"=>"4", "data-source"=>"[&quot;designer&quot;,&quot;Attorney&quot;,&quot;painter&quot;,&quot;Accountant&quot;]".html_safe %>
<%end%>

app/views/users/_ways_to_connect.html.erb
<h2 class="form-signin-heading">Ways to connect<h2>
<%= f.text_field :email, :class => "input-block-level", :placeholder => "Email" %>
<br>	
<%= f.text_field :google_plus_profile_url, :class => "input-block-level", :placeholder => "Google Plus" %>
<br>
<%= f.text_field :skype, :class => "input-block-level", :placeholder => "Skype" %>
<br>	
<%= f.text_field :phone, :class => "input-block-level", :placeholder => "Phone" %>
<br>

app/views/users/edit.html.erb
<div class="container">
	<%= render "form"%>
</div>

app/views/users/new.html.erb
<div class="container">
	<%= form_for @user, :html => { :class => "form-signin"} do |f| %>
		<%= render "about", :f => f %>
		<%= render "need", :f => f %>	
		<%= render "offering", :f => f %>	
		<%= render "ways_to_connect", :f => f %>		
	  <p><%= f.submit "Continue", :class => "btn btn-large btn-primary"  %></p>
	<%end%>
</div>

app/views/users/profile.html.erb
<div class="container profile-container" style="background-color:#E7E7E7;">
    <% if user_signed_in?%>
        <%= link_to "Sign Out", destroy_user_session_path, :method => :delete , :style => "float:right;margin-top:20px;margin-right:20px;", :class => "btn btn-primary"%>
    <%end%>
	
	<div class="row" style="margin-top:40px;">
		<div class="span3">
            <%= link_to @user.name, edit_user_path(@user), :style => "margin-left:40px;margin-top:20px;"%>
			<%= image_tag(image_url(@user), :class=>"img-polaroid", :hieght => 140, :width => 140, :style => "margin-left:40px;" ) %>
			<h4 style = "margin-left:40px" >Zip: <%= @user.zip_code%><h4>
			<h5><%= link_to "Linked in profile", @user.linked_public_profile, :style => "margin-left:40px;" %></h5>
			<h5><%= link_to "Google+", @user.google_plus_profile_url, :style => "margin-left:40px;"%></h5>
			<h5><%= link_to "Comapany Website", @user.company_url, :style => "margin-left:40px;"%></h5>						
		</div>
		<div class=span6>
			<div class="row">
				<div class="span3">
					<h5>Needs</h5>
            <ul>
              <% @user.needs.each do |need|%>
                <% if need.title.present? %>
                  <li><%= need.title %></li>
                <%end%>
              <%end%>
    			  </ul>
				</div>
				<div class="span3">
					<h5>Offerings</h5>
					<ul>
            <% @user.offerings.each do |offering|%>
              <% if offering.title.present? %>
                <li><%= offering.title%></li>
              <%end%>  
            <%end%>
    			</ul>
				</div>				
			</div>
			<h5>About Bob</h5>
    		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
    	<h5>Top Matches</h5>
        <% offers_matching(@user).each do |offer| %>
          <div class="row">
            <div class="span1">
                <%= image_tag(offer.user.linked_in_image_url, :class=>"img-polaroid", :hieght => 150, :width => 90) %>
            </div>
            <div class="span5">
                <%= link_to offer.user.name, offer.user.linked_public_profile%>
                <h6>Needs: <%= user_needs(@user)%></h6>
                <h6>Offering: <%= user_offerings(user)%></h6>
            </div>          
          </div>
        <%end%>
        <% needs_matching(@user).each do |offer| %>
          <div class="row">
              <div class="span1">
                <%= image_tag(offer.user.linked_in_image_url, :class=>"img-polaroid", :hieght => 150, :width => 90) %>
              </div>
              <div class="span5">
                <%= link_to offer.user.name, offer.user.linked_public_profile%>
                <h6>Needs: <%= user_needs(@user)%></h6>
                <h6>Offering: <%= user_offerings(user)%></h6>
              </div>          
          </div>
        <%end%>
      <div class="row">
        <div class="span1">
          <%= image_tag("Profile-Picture.png", :class=>"img-polaroid", :hieght => 150, :width => 90) %>
        </div>
        <div class="span5">
          <%= link_to "Mike Jones"%>
          <h6>Needs: IT Consulting, Plumbing, Handyman Work</h6>
          <h6>Offering: Professional Services, Scrapbook services</h6>
        </div>        
      </div>
    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
		<div class="row">
    		<div class="span1">
    			<%= image_tag("Profile-Picture.png", :class=>"img-polaroid", :hieght => 150, :width => 90) %>
    		</div>
    		<div class="span5">
    			<%= link_to "Mike Jones"%>
    			<h6>Needs: IT Consulting, Plumbing, Handyman Work</h6>
    			<h6>Offering: Professional Services, Scrapbook services</h6>
    		</div>    		
    	</div>
    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
    	<div class="row">
				<div class="span3">
					<h5>Upcoming Meetings</h5>
					<ol>
            <% upcoming_meetings(@user).each do |meeting| %>
              <li><%= "#{meeting_with}" "#{meeting.meeting_time} "%></li>
            <%end%>
    			</ol>
				</div>
				<div class="span3">
					<h5>Past Meetings</h5>
					<ol>
            <% past_meetings(@user).each do |meeting| %>
              <li><%= "#{meeting_with}" "#{meeting.meeting_time} "%></li>
            <%end%>
    			</ol>
				</div>				
			</div>    		
		</div>
	</div>
</div>

app/views/users/sign_up.html.erb
<%= form_for @user do |f| %>
	<%= render "#{@user.current_step}", :f => f %>
<!-- 	<%= render :partial => "about", :locals => {:f => f}%>
	<%= render :partial => "offering"%>
	<%= render :partial => "need"%>
	<%= render :partial => "ways_to_connect"%>	 -->	
	<%= f.submit "Next"%>			
<%end%>	

app/views/users/sign_up_success.html.erb
<div class="form-signin">
	<h3>Congrats</h3>
	You're all done. Now get ready for us to do all the work and find you what you are looking for.
	<div class=""> 
		<%= link_to "View Your Profile", profile_user_path(@user), :class => "btn btn-block  btn-large btn-primary"%>
	</div>
</div>